/*
*	Admin: Arvind Krishna
*	github - github.com/ArvindAROO
*	type - c_project
* 	client side file of the project
*/

//All the includes
#include<stdio.h>
#include<stdlib.h>
#include<ctype.h>
#include<time.h>

#include"server.h"

int main(void){
	//The main function
	//Creating the instance for all the structures
	//And defining the variables
    airport AirPort;
    int i, numOfPlanes, presentTime, TotalTime ;
    double expectarrive, expectdepart ;
    plane temp;
    //Initializing the airport
    initializeAirport(&AirPort);
	//Starting
    start(&TotalTime, &expectarrive, &expectdepart);
	//Outer for loop manages the number of iterations, which is a count of time
	//Effectively, 1 iteration is 1 unit of time
    for(presentTime = 1 ; presentTime <= TotalTime ; presentTime++){
        numOfPlanes = randomnumber();
        //The num of planes for every iteration is
		//randomly generated by using a bit complex random function
		for(i = 0 ; i < numOfPlanes ; i++){
			//This is generation of planes
        	//of course random number of times
            createNewPlane(&AirPort, presentTime, DEPART);
        	//For every iteration a new plane will be genarate
        	//and added to the landing queue if and only if
        	//the airport is empty and there is no plane to be landed
            if(isFullAirport(AirPort, DEPART))
               refuseLand(&AirPort);
               //The plane will be refused to be allowed to
               //take off if the airport is not empty
            else
               airportAddToQueue(&AirPort, DEPART);
               //Will be alllowed to take off if the airport is empty
        }

        numOfPlanes = randomnumber();
		//The num of planes for every iteration is
		//randomly generated by using a bit complex random function
        for(i = 0 ; i < numOfPlanes ; i++){
        	//This is generation of planes
        	//of course random number of times
        	//For every iteration a new plane will be genarate
        	//and added to the landing queue
            createNewPlane(&AirPort, presentTime, ARRIVE);
			airportAddToQueue(&AirPort, ARRIVE);
        }


        //Here, the generation of planes is complete
        //Its time to either land or take them off
        if(!(isEmptyAirport(AirPort, ARRIVE))){
        	//If landing is possible
            while(!isEmptyAirport(AirPort, ARRIVE)){
            	//All the planes necessary to land will be landed
                temp = airportPopQueue(&AirPort, ARRIVE);
                land(&AirPort, temp, presentTime);
            }
        } else if(!(isEmptyAirport(AirPort, DEPART))) {
        	//Take off will not be allowed for all at the same time
            temp = airportPopQueue(&AirPort, DEPART);
            fly(&AirPort, temp, presentTime);
    	}else{
    		//If there is no plane to land or takeoff,
    		//the runway is idle
        	idle(&AirPort, presentTime);
		}
		delay(0.25);
		//mimicing the sleep function

    }
	//After each iteration, a unit of time passes

	//Calling the result function
    Result(&AirPort, TotalTime);
	//clearing the screen
    clrscr();
    printf("Thanks\nBy,\n\tArvind Krishna\a");
    printf("\ngithub.com/ArvindAROO\n\n");
    //Displaying creator info
	return 0;
}
